<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2024-2026 Bundesdruckerei GmbH
    For the license see the accompanying file LICENSE.MD.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>de.bdr.pidi</groupId>
    <artifactId>status-list-service</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>status-list-service</name>
    <inceptionYear>2024</inceptionYear>
    <description>PID-Issuer / PID-Provider Status-List-Service</description>
    <properties>
        <java.version>25</java.version>
        <kotlin.version>2.4.10</kotlin.version>
        <openapi.version>7.22.0</openapi.version>
        <kotlin.compiler.daemon>false</kotlin.compiler.daemon>
        <aspectj.version>1.9.25.1</aspectj.version>
        <opentelemetry-logback-mdc-1.0.version>2.16.0-alpha</opentelemetry-logback-mdc-1.0.version>
        <logbook-spring-boot-starter.version>4.0.4</logbook-spring-boot-starter.version>
        <nimbus-jose-jwt.version>10.9.1</nimbus-jose-jwt.version>
        <jacoco-maven-plugin.version>0.8.15</jacoco-maven-plugin.version>
        <aspectj-maven-plugin.version>1.14.1</aspectj-maven-plugin.version>
        <mockk.version>1.14.11</mockk.version>
        <springmockk.version>5.0.1</springmockk.version>
        <assertk-jvm.version>0.28.1</assertk-jvm.version>
        <awaitility-kotlin.version>4.3.0</awaitility-kotlin.version>
        <license.maven.plugin.version>5.1.1</license.maven.plugin.version>
        <jackson-module-kotlin.version>3.2.1</jackson-module-kotlin.version>
        <netty.version>4.2.16.Final</netty.version>
        <bouncycastle-bc-jdk18on.version>1.85</bouncycastle-bc-jdk18on.version>
        <postgresql.version>42.7.12</postgresql.version>
        <jackson-bom.version>3.2.1</jackson-bom.version>
        <jackson-2-bom.version>2.22.1</jackson-2-bom.version>
        <log4j2.version>2.25.5</log4j2.version>

        <sonar.version>5.7.0.6970</sonar.version>
        <sonar.projectKey>de.bdr.pidi.status-list-service</sonar.projectKey>
        <sonar.coverage.jacoco.xmlReportPaths>target/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <sonar.sources>src/main/kotlin,pom.xml</sonar.sources>
        <sonar.tests>src/test/kotlin</sonar.tests>
        <sonar.junit.reportPaths>target/surefire-reports/</sonar.junit.reportPaths>
        <sonar.sarifReportPaths>roxctl_results.sarif</sonar.sarifReportPaths>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aspectj</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
        </dependency>
        <dependency>
            <groupId>de.bundesdruckerei.mdoc.kotlin</groupId>
            <artifactId>mdoc-core-jvm</artifactId>
            <version>0.22.1</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/mdoc-core-jvm-0.22.1.jar</systemPath>
            <exclusions>
                <exclusion>
                    <!--  CVE-2020-3684 net.i2p.crypto:eddsa used in:
                    +- de.bundesdruckerei.mdoc.kotlin:mdoc-core-jvm:jar:0.19.0:compile
                    |  +- com.augustcellars.cose:cose-java:jar:1.1.0:compile
                    |  |  \- net.i2p.crypto:eddsa:jar:0.3.0:compile
                    so we exclude it because it is not used anyway -->
                    <groupId>net.i2p.crypto</groupId>
                    <artifactId>eddsa</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.augustcellars.cose</groupId>
            <artifactId>cose-java</artifactId>
            <version>1.1.0</version>
            <exclusions>
                <exclusion>
                    <!--  CVE-2020-3684 net.i2p.crypto:eddsa used in:
                    +- com.augustcellars.cose:cose-java:jar:1.1.0:compile
                    |  \- net.i2p.crypto:eddsa:jar:0.3.0:compile
                    so we exclude it because it is not used anyway -->
                    <groupId>net.i2p.crypto</groupId>
                    <artifactId>eddsa</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>10.9.1</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
            <version>${bouncycastle-bc-jdk18on.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
            <version>2.0.13</version>
        </dependency>
        <dependency>
            <groupId>tools.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-docker-compose</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-logback-mdc-1.0</artifactId>
            <version>${opentelemetry-logback-mdc-1.0.version}</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.zalando</groupId>
            <artifactId>logbook-spring-boot-starter</artifactId>
            <version>${logbook-spring-boot-starter.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <!-- Test dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-restclient-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jdbc-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-serialization-json</artifactId>
            <version>1.11.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.willowtreeapps.assertk</groupId>
            <artifactId>assertk-jvm</artifactId>
            <version>${assertk-jvm.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility-kotlin</artifactId>
            <version>${awaitility-kotlin.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.ninja-squad</groupId>
            <artifactId>springmockk</artifactId>
            <version>${springmockk.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.mockk</groupId>
            <artifactId>mockk</artifactId>
            <version>${mockk.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <outputDirectory>${project.build.directory}/unwoven-classes</outputDirectory>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <configuration>
                    <args>
                        <arg>-Xjsr305=strict</arg>
                    </args>
                    <compilerPlugins>
                        <plugin>spring</plugin>
                        <plugin>kotlinx-serialization</plugin>
                    </compilerPlugins>
                    <sourceDirs>
                        <sourceDir>${project.build.directory}/generated/src/main/kotlin</sourceDir>
                    </sourceDirs>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-serialization</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>src/test/kotlin</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi.version}</version>
                <executions>
                    <execution>
                        <id>generate-external</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>status-list-service.openapi.yml</inputSpec>
                            <output>${project.build.directory}/generated</output>
                            <generatorName>kotlin-spring</generatorName>
                            <apiPackage>de.bdr.statuslist.web.api</apiPackage>
                            <modelPackage>de.bdr.statuslist.web.api.model</modelPackage>
                            <packageName>de.bdr.statuslist.web</packageName>
                            <templateDirectory>src/main/resources/templates</templateDirectory>
                            <addCompileSourceRoot>false</addCompileSourceRoot>
                            <configOptions>
                                <documentationProvider>none</documentationProvider>
                                <interfaceOnly>true</interfaceOnly>
                                <dateLibrary>java8</dateLibrary>
                                <useSpringBoot3>true</useSpringBoot3>
                                <exceptionHandler>false</exceptionHandler>
                                <useBeanValidation>false</useBeanValidation>
                                <useTags>true</useTags>
                                <gradleBuildFile>false</gradleBuildFile>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-internal</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>status-list-service.openapi.intern.yml</inputSpec>
                            <output>${project.build.directory}/generated</output>
                            <generatorName>kotlin-spring</generatorName>
                            <apiPackage>de.bdr.statuslist.web.api</apiPackage>
                            <modelPackage>de.bdr.statuslist.web.api.model</modelPackage>
                            <packageName>de.bdr.statuslist.web</packageName>
                            <addCompileSourceRoot>false</addCompileSourceRoot>
                            <configOptions>
                                <apiSuffix>InternalApi</apiSuffix>
                                <documentationProvider>none</documentationProvider>
                                <interfaceOnly>true</interfaceOnly>
                                <dateLibrary>java8</dateLibrary>
                                <useSpringBoot3>true</useSpringBoot3>
                                <exceptionHandler>false</exceptionHandler>
                                <useBeanValidation>false</useBeanValidation>
                                <useTags>true</useTags>
                                <gradleBuildFile>false</gradleBuildFile>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skip>${skipUnitTests}</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>dev.aspectj</groupId>
                <artifactId>aspectj-maven-plugin</artifactId>
                <version>${aspectj-maven-plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjtools</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                <complianceLevel>${java.version}</complianceLevel>
                <forceAjcCompile>true</forceAjcCompile>
                    <weaveDirectories>
                        <weaveDirectory>${project.build.directory}/unwoven-classes</weaveDirectory>
                    </weaveDirectories>
                </configuration>
                <executions>
                    <execution>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-maven-plugin.version}</version>
                <configuration>
                    <append>true</append>
                    <dumpOnExit>true</dumpOnExit>
                    <fileSets>
                        <fileSet>
                            <directory>${project.build.directory}</directory>
                            <includes>
                                <include>*.exec</include>
                            </includes>
                        </fileSet>
                    </fileSets>
                </configuration>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>${license.maven.plugin.version}</version>
                <configuration>
                    <licenseSets>
                        <licenseSet>
                            <inlineHeader>
                                Copyright $${license.git.copyrightYears} Bundesdruckerei GmbH
For the license see the accompanying file LICENSE.MD.
                            </inlineHeader>
                            <excludes>
                                <exclude>**/*.pem</exclude>
                                <exclude>**/*.crt</exclude>
                                <exclude>**/*.key</exclude>
                                <exclude>**/*.csr</exclude>
                                <exclude>.m2/**/*</exclude>
                                <exclude>**/*-log.txt</exclude>
                                <exclude>.run/*</exclude>
                                <exclude>**/*.tgz</exclude>
                                <exclude>**/*.lock</exclude>
                                <exclude>db/migrations/*.sql</exclude>
                                <exclude>junit-merge.sh</exclude>
                                <exclude>**/*.sh</exclude>
                                <exclude>**/*.mustache</exclude>
                                <exclude>**/type</exclude>
                                <exclude>**/*.cbor</exclude>
                            </excludes>
                        </licenseSet>
                    </licenseSets>
                    <strictCheck>true</strictCheck>
                    <aggregate>true</aggregate>
                    <mapping>
                        <feature>SCRIPT_STYLE</feature>
                        <http>SCRIPT_STYLE</http>
                        <txt>SCRIPT_STYLE</txt>
                    </mapping>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.mycila</groupId>
                        <artifactId>license-maven-plugin-git</artifactId>
                        <version>${license.maven.plugin.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>${sonar.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>jacoco</id>
            <activation>
                <activeByDefault>false</activeByDefault>
                <property>
                    <name>jacoco</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <jvmArguments>${argLine}</jvmArguments>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
