#
# Copyright 2024-2026 Bundesdruckerei GmbH
# For the license see the accompanying file LICENSE.MD.
#

logging:
  level:
    org.zalando.logbook: ${HTTP_LOGGING:off}

logbook:
  predicate:
    include:
      - path: /**
        methods:
          - GET
          - POST
          - PUT
          - DELETE
  filter.enabled: true
  format.style: http
  strategy: body-only-if-status-at-least
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
      - X-Api-Key

spring:
  web:
    error:
      whitelabel:
        enabled: false

management:
  server:
    port: 9090
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
    prometheus:
      access: read-only
    loggers:
      access: read-only
  endpoints:
    access.default: none
    web:
      exposure:
        include: 'health, prometheus, loggers'
  prometheus:
    metrics:
      export:
        enabled: true
